# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

def shared_pods
  pod 'XCGLogger'
  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'SnapKit'
  pod 'ReachabilitySwift'
end

target 'ItunesExample' do
  # Pods for ItunesExample
  shared_pods
  pod 'RxCocoa'

  target 'ItunesExampleTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
    #pod 'RxBlocking'
    #pod 'RxTest'
  end

end

#Workaround to supress cocoa pods warnings in xcode 12
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
	if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
  end
end
